services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'

#  keycloak:
#    image: 'quay.io/keycloak/keycloak:25.0.2'
#    environment:
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#    ports:
#      - '8082:8080'
#    command: ["start-dev"]

  victoria-metrics:
    image: 'victoriametrics/victoria-metrics:v1.93.12'
    ports:
      - '8428:8428'
    volumes:
      - './configs/victoria-metrics/promscrape.yaml:/promscrape.yaml'
    command:
      - '-promscrape.config=promscrape.yaml'