spring:
  application:
    name: todo-app
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/todo
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/todo
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: todo-app
            client-secret: wF9HVUD7HjmYBb5HW9jURPjQsy1s2faN
            scope:
              - openid
              - task_view
              - task_edit
              - microprofile-jwt
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      start:
        log-level: info
        command: up
      stop:
        command: stop

  profiles:
    active: prod

server:
  port: 8081

