scrape_configs:
  - job_name: todo-task-service
    static_configs:
      - targets:
          - http://192.168.0.105:8081/actuator/prometheus
    oauth2:
      client_id: victoria-metrics-keycloak
      client_secret: SiMxtWmgXDwktFG1BXALEQIOZvRU0n6v
      token_url: http://192.168.0.105:8082/realms/todo/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials