spring:
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: task-service
          service-host-type: ip
        url: http://localhost:8083
  application:
    name: todo-app
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/todo
#          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8082/realms/todo
#            user-name-attribute: preferred_username
#        registration:
#          keycloak:
#            client-id: todo-app
#            client-secret: wF9HVUD7HjmYBb5HW9jURPjQsy1s2faN
#            scope:
#              - openid
#              - task_view
#              - task_edit
#              - microprofile-jwt
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      start:
        log-level: info
        command: up
      stop:
        command: stop

logging:
  profiles:
    active: prod
  level:
    org.springframework.security: DEBUG
    org.keycloak: DEBUG

springdoc:
  swagger-ui:
    oauth:
      client-id: todo-app-swagger-ui
      use-pkce-with-authorization-code-grant: true

keycloak:
  uri: http://localhost:8082

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: '*'

server:
  port: 8081

